import type { Metadata } from "next";

import { Providers } from "@/app/providers";

import { Inter } from "next/font/google";

import "@/app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <Providers>
                <body className={`${inter.className} antialiased`}>
                    <main className="flex flex-col gap-8">{children}</main>
                </body>
            </Providers>
        </html>
    );
}
