import type { Metadata } from "next";

import { Navbar } from "@/components/common";

import { Inter } from "next/font/google";

import "@/app/globals.css";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <Providers>
                <body className={`${inter.className} antialiased`}>
                    <Navbar />
                    <main className="mx-auto flex flex-col gap-8 pb-8">{children}</main>
                </body>
            </Providers>
        </html>
    );
}
